steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/sarath-gke/dockerfiles/sample-app:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/sarath-gke/dockerfiles/sample-app:latest']

images:
  - 'us-central1-docker.pkg.dev/sarath-gke/dockerfiles/sample-app:latest'
